services:
  app:
    image: tbelzbby/vester
    ports:
      - "5000:5000"
    environment:
      DATABASE_URI: ${POSTGRES_DB_URI}
      FLASK_APP: ${FLASK_APP}
      UPLOAD_FOLDER: ${UPLOAD_FOLDER}
      ALLOWED_EXTENSIONS: ${ALLOWED_EXTENSIONS}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - redis
      - celery
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A celery_worker.app worker --loglevel=info
    environment:
      REDIS_URL: ${REDIS_URL}
      PYTHONPATH: /app
    depends_on:
      - redis
    volumes:
      - ./storage/uploads:/app/storage/uploads
    networks:
      - badafeez

networks:
  badafeez:
    driver: bridge

volumes:
  db_data: