name: tbelzbby/vester

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up environment variables
        run: |
          echo "FLASK_APP=${{ secrets.FLASK_APP }}" >> $GITHUB_ENV
          echo "POSTGRES_DB_URI=${{ secrets.POSTGRES_DB_URI }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover tests/

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Create .env file dynamically, if required
      - name: Create .env file dynamically
        run: |
          echo "POSTGRES_DB_URI=${{ secrets.POSTGRES_DB_URI }}" > .env
          echo "FLASK_APP=${{ secrets.FLASK_APP }}" >> .env
          echo "FLASK_ENV=${{ secrets.FLASK_ENV }}" >> .env
          echo "UPLOAD_FOLDER=${{ secrets.UPLOAD_FOLDER }}" >> .env
          echo "ALLOWED_EXTENSIONS=${{ secrets.ALLOWED_EXTENSIONS }}" >> .env
          echo "MAX_FILE_SIZE=${{ secrets.MAX_FILE_SIZE }}" >> .env

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/vester:${{ github.sha }} -t ${{ secrets.DOCKER_HUB_USERNAME }}/vester:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vester:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vester:${{ github.sha }}
